openapi: 3.0.3
info:
  title: 'Test Case Study Documentation'
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
paths:
  /api/products:
    get:
      summary: 'Ürünleri Listele'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                example:
                  -
                    id: 1
                    category: 1
                    name: 'Black&Decker A7062 40 Parça Cırcırlı Tornavida Seti'
                    price: 120.75
                    stock: 10
                    created_at: '2022-07-11T19:15:47.000000Z'
                    updated_at: '2022-07-11T19:15:47.000000Z'
                  -
                    id: 2
                    category: 1
                    name: "Reko Mini Tamir Hassas Tornavida Seti 32'li"
                    price: 49.5
                    stock: 10
                    created_at: '2022-07-11T19:15:47.000000Z'
                    updated_at: '2022-07-11T19:15:47.000000Z'
                  -
                    id: 3
                    category: 2
                    name: 'Viko Karre Anahtar - Beyaz'
                    price: 11.28
                    stock: 10
                    created_at: '2022-07-11T19:15:47.000000Z'
                    updated_at: '2022-07-11T19:15:47.000000Z'
                  -
                    id: 4
                    category: 2
                    name: 'Legrand Salbei Anahtar, Alüminyum'
                    price: 22.8
                    stock: 10
                    created_at: '2022-07-11T19:15:47.000000Z'
                    updated_at: '2022-07-11T19:15:47.000000Z'
                  -
                    id: 5
                    category: 2
                    name: 'Schneider Asfora Beyaz Komütatör'
                    price: 12.95
                    stock: 10
                    created_at: '2022-07-11T19:15:47.000000Z'
                    updated_at: '2022-07-11T19:15:47.000000Z'
      tags:
        - Ürünler
      security: []
  /api/orders:
    get:
      summary: 'Siparis Listeleme'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                example:
                  -
                    id: 1
                    customerId: 1
                    items:
                      -
                        productId: 102
                        quantity: 10
                        unitPrice: '11.28'
                        total: '112.80'
                    total: 112.8
                    created_at: '2022-07-11T19:15:47.000000Z'
                    updated_at: '2022-07-11T19:15:47.000000Z'
                  -
                    id: 2
                    customerId: 2
                    items:
                      -
                        productId: 101
                        quantity: 2
                        unitPrice: '49.50'
                        total: '99.00'
                      -
                        productId: 100
                        quantity: 1
                        unitPrice: '120.75'
                        total: '120.75'
                    total: 219.75
                    created_at: '2022-07-11T19:15:47.000000Z'
                    updated_at: '2022-07-11T19:15:47.000000Z'
                  -
                    id: 3
                    customerId: 3
                    items:
                      -
                        productId: 102
                        quantity: 6
                        unitPrice: '11.28'
                        total: '67.68'
                      -
                        productId: 100
                        quantity: 10
                        unitPrice: '120.75'
                        total: '1207.50'
                    total: 1275.18
                    created_at: '2022-07-11T19:15:47.000000Z'
                    updated_at: '2022-07-11T19:15:47.000000Z'
      tags:
        - Siparişler
      security: []
    post:
      summary: 'Siparis Ekleme'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Siparişler
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                consumerId:
                  type: integer
                  description: ''
                  example: 14
                items:
                  type: array
                  description: ''
                  example:
                    - []
                  items:
                    type: object
                    properties:
                      productId:
                        type: integer
                        description: ''
                        example: 11
                      quantity:
                        type: integer
                        description: ''
                        example: 3
                      unitPrice:
                        type: number
                        description: ''
                        example: 1765.9477595
                      total:
                        type: number
                        description: ''
                        example: 0.846325
                    required:
                      - productId
                      - quantity
                      - unitPrice
                      - total
                total:
                  type: number
                  description: ''
                  example: 0.0
              required:
                - consumerId
                - items
                - total
      security: []
  '/api/orders/{id}':
    delete:
      summary: 'Siparis Silme'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Siparişler
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the order.'
        example: 15
        required: true
        schema:
          type: integer
tags:
  -
    name: Ürünler
    description: ''
  -
    name: Siparişler
    description: ''
