openapi: 3.0.3
info:
  title: 'Test Case Study Documentation'
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
paths:
  /api/discounts:
    get:
      summary: 'Butun kurallari getir'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                example:
                  -
                    id: 1
                    name: '10 percent over 1000'
                    type: cart
                    filters: null
                    rule: '{"condition":"{cart.total} >= 1000","amount":"{cart.total} * 0.1"}'
                    expired_at: null
                    created_at: '2022-07-14T23:06:30.000000Z'
                    updated_at: '2022-07-14T23:06:30.000000Z'
                  -
                    id: 2
                    name: 'Buy 5 get 1 in category id 2'
                    type: product
                    filters: null
                    rule: '{"condition":"{product.category} == 2 && {product.quantity} == 6","amount":"{product.unitPrice}"}'
                    expired_at: null
                    created_at: '2022-07-14T23:06:30.000000Z'
                    updated_at: '2022-07-14T23:06:30.000000Z'
                  -
                    id: 3
                    name: 'Buy atleast 2 get %20 discount for the cheapest item in category id 2'
                    type: cart
                    filters: '{"category":1}'
                    rule: '{"condition":"{cart.quantity} >= 2","amount":"{cart.cheapest} * 0.2"}'
                    expired_at: null
                    created_at: '2022-07-14T23:06:30.000000Z'
                    updated_at: '2022-07-14T23:06:30.000000Z'
      tags:
        - 'Indirim Kurallari'
      security: []
  '/api/discounts/{order_id}':
    get:
      summary: 'Sipariş için indirim hesapla'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            text/plain:
              schema:
                type: string
                example: ''
      tags:
        - 'Indirim Kurallari'
      security: []
    parameters:
      -
        in: path
        name: order_id
        description: 'Optional parameter. Sipariş id (order_id)'
        required: true
        schema:
          type: integer
        examples:
          omitted:
            summary: 'When the value is omitted'
            value: ''
          present:
            summary: 'When the value is present'
            value: 6
  /api/orders:
    get:
      summary: 'Siparis Listeleme'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                example:
                  -
                    id: 1
                    customerId: 1
                    items:
                      -
                        productId: 102
                        quantity: 10
                        unitPrice: '11.28'
                        total: '112.80'
                    total: 112.8
                    created_at: '2022-07-12T15:14:16.000000Z'
                    updated_at: '2022-07-12T15:14:16.000000Z'
      tags:
        - Siparişler
      security: []
    post:
      summary: 'Siparis Ekleme'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Siparişler
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                customerId:
                  type: integer
                  description: ''
                  example: 18
                items:
                  type: array
                  description: ''
                  example:
                    - []
                  items:
                    type: object
                    properties:
                      productId:
                        type: integer
                        description: ''
                        example: 16
                      quantity:
                        type: integer
                        description: ''
                        example: 16
                    required:
                      - productId
                      - quantity
              required:
                - customerId
                - items
      security: []
  '/api/orders/{id}':
    delete:
      summary: 'Siparis Silme'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses: {  }
      tags:
        - Siparişler
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the order.'
        example: 1
        required: true
        schema:
          type: integer
  /api/products:
    get:
      summary: 'Ürünleri Listele'
      description: 'Ürünler için şimdilik sadece listeleme özelliği bulunmaktadır.'
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                example:
                  -
                    id: 100
                    category: 1
                    name: 'Black&Decker A7062 40 Parça Cırcırlı Tornavida Seti'
                    price: 120.75
                    stock: 10
                    created_at: '2022-07-12T15:14:16.000000Z'
                    updated_at: '2022-07-12T15:14:16.000000Z'
      tags:
        - Ürünler
      security: []
tags:
  -
    name: 'Indirim Kurallari'
    description: ''
  -
    name: Siparişler
    description: ''
  -
    name: Ürünler
    description: ''
